name: share_my_apk
description: "🚀 The ultimate Flutter APK build & upload automation tool. One command builds, organizes, and uploads APKs to Diawi/Gofile with smart provider switching. Production-ready with 100+ tests, comprehensive error handling, and enterprise-grade reliability. Perfect for CI/CD pipelines and development workflows."
version: 1.0.0

# Package metadata for pub.dev
homepage: https://github.com/wm-jenildgohel/share_my_apk
repository: https://github.com/wm-jenildgohel/share_my_apk
documentation: https://pub.dev/documentation/share_my_apk/latest/
issue_tracker: https://github.com/wm-jenildgohel/share_my_apk/issues


# Topics for better discoverability
topics:
  - apk-builder
  - android
  - upload
  - flutter
  - cli
  - automation
  - build-tool
  - devops
  - ci-cd
  - deployment

platforms: 
  android:

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.7.0
  http: ^1.4.0
  intl: ^0.20.2
  logging: ^1.3.0
  meta: ^1.15.0
  path: ^1.9.1
  process_run: ^1.2.4
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  mockito: ^5.4.4
  build_runner: ^2.4.12

executables:
  share_my_apk:
